### ISSUE TITLE
Visualization of Figure 1

### ISSUE THREAD

**Issue by yuan-zm** [martianxiu/DiffusionUnit#2]
Hi @martianxiu,

After reading your code, I really curious about the visualization of Fig. 1.

Here https://github.com/martianxiu/DiffusionUnit/blob/6532ef0f86a0a932e0a4722a7498e38557e535f8/model/blocks.py#L192, the output of the DU block is a BxCxN tensor. So, how to visualize it?

**Comment by martianxiu** [comment]
Hi @dream-toy , thank you for your comment. Actually the output shape is (BxN, C) rather than (B, C, N). Note that N denotes the number of input points per sample and can be different for different samples. You can check [here](https://github.com/POSTECH-CVLab/point-transformer/issues/36) for more details. 
For Fig.1 visualization, the detailed steps are written in Section IV.A in our arxiv paper.

**Comment by yuan-zm** [comment]
Thank you for your reply. I see, it is the visualization of ||f_n - f_s||.
